/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "What's New in Azure Architecture Center",
      "frontmatter": {
        "title": "What's New in Azure Architecture Center",
        "description": "New and updated articles in Azure Architecture Center",
        "author": "changeUserName",
        "ms.date": "01/12/2021",
        "ms.topic": "article",
        "ms.service": "architecture-center",
        "ms.subservice": "meta"
      },
      "regularPath": "/changelog.html",
      "relativePath": "changelog.md",
      "key": "v-24b8768f",
      "path": "/changelog.html",
      "headers": [
        {
          "level": 2,
          "title": "January 2021",
          "slug": "january-2021"
        },
        {
          "level": 3,
          "title": "Updated Articles",
          "slug": "updated-articles"
        },
        {
          "level": 2,
          "title": "September 2020",
          "slug": "september-2020"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "logo.png",
        "heroText": "A CSS framework by Otabek Sadiridinov",
        "tagline": "Easy to use,lightweight, class based...",
        "actionText": "Get started 👈",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Easy to use",
            "details": "Feature 1 Description"
          },
          {
            "title": "Lightweight",
            "details": "Feature 2 Description"
          },
          {
            "title": "Class based & etsc",
            "details": "Feature 3 Description"
          }
        ],
        "footer": "Made by Otabek Sadiridinov with ❤️"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-be4232e8",
      "path": "/",
      "lastUpdated": "1/7/2021, 9:09:30 PM"
    },
    {
      "title": "Config",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/config/",
      "relativePath": "config/README.md",
      "key": "v-f6c8ada2",
      "path": "/config/",
      "headers": [
        {
          "level": 2,
          "title": "foo",
          "slug": "foo"
        },
        {
          "level": 2,
          "title": "bar",
          "slug": "bar"
        }
      ]
    },
    {
      "title": "Introduction",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-3b39481f",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "What is ZeroUI.",
          "slug": "what-is-zeroui"
        },
        {
          "level": 2,
          "title": "Installation",
          "slug": "installation"
        },
        {
          "level": 3,
          "title": "1.Directly with tags",
          "slug": "_1-directly-with-tags"
        },
        {
          "level": 3,
          "title": "2.Using CDN",
          "slug": "_2-using-cdn"
        },
        {
          "level": 3,
          "title": "3.Install via NPM/Yarn",
          "slug": "_3-install-via-npm-yarn"
        },
        {
          "level": 2,
          "title": "And more",
          "slug": "and-more"
        }
      ]
    },
    {
      "title": "Button",
      "frontmatter": {},
      "regularPath": "/guide/button.html",
      "relativePath": "guide/button.md",
      "key": "v-1a528864",
      "path": "/guide/button.html"
    },
    {
      "title": "Using components",
      "frontmatter": {},
      "regularPath": "/guide/components.html",
      "relativePath": "guide/components.md",
      "key": "v-134e7b1c",
      "path": "/guide/components.html",
      "headers": [
        {
          "level": 2,
          "title": "Hello",
          "slug": "hello"
        },
        {
          "level": 2,
          "title": "Hi",
          "slug": "hi"
        }
      ]
    },
    {
      "title": "CSS classes",
      "frontmatter": {},
      "regularPath": "/guide/css-classes.html",
      "relativePath": "guide/css-classes.md",
      "key": "v-d5b58d3c",
      "path": "/guide/css-classes.html"
    },
    {
      "title": "Fonts",
      "frontmatter": {},
      "regularPath": "/guide/fonts.html",
      "relativePath": "guide/fonts.md",
      "key": "v-5b20f722",
      "path": "/guide/fonts.html",
      "headers": [
        {
          "level": 2,
          "title": "Default font",
          "slug": "default-font"
        },
        {
          "level": 2,
          "title": "Offered fonts",
          "slug": "offered-fonts"
        },
        {
          "level": 2,
          "title": "How to change the font?",
          "slug": "how-to-change-the-font"
        },
        {
          "level": 2,
          "title": "How to add a new font?",
          "slug": "how-to-add-a-new-font"
        }
      ]
    },
    {
      "title": "Using Vue in Markdown",
      "frontmatter": {},
      "regularPath": "/guide/how-to-use.html",
      "relativePath": "guide/how-to-use.md",
      "key": "v-04a8e3a4",
      "path": "/guide/how-to-use.html",
      "headers": [
        {
          "level": 2,
          "title": "Browser API Access Restrictions",
          "slug": "browser-api-access-restrictions"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    },
    {
      "title": "Text styling",
      "frontmatter": {},
      "regularPath": "/guide/text-styling.html",
      "relativePath": "guide/text-styling.md",
      "key": "v-2fe3a0ec",
      "path": "/guide/text-styling.html",
      "headers": [
        {
          "level": 2,
          "title": "Headings",
          "slug": "headings"
        },
        {
          "level": 2,
          "title": "Paragraphs",
          "slug": "paragraphs"
        },
        {
          "level": 2,
          "title": "Small style text",
          "slug": "small-style-text"
        },
        {
          "level": 2,
          "title": "Font weights",
          "slug": "font-weights"
        },
        {
          "level": 2,
          "title": "Font styles",
          "slug": "font-styles"
        },
        {
          "level": 2,
          "title": "Text decoration",
          "slug": "text-decoration"
        },
        {
          "level": 2,
          "title": "Aligning text",
          "slug": "aligning-text"
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "",
    "logo": "/logo-text.png",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": false,
    "nav": [
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "Config",
        "link": "/config/"
      },
      {
        "text": "VuePress",
        "link": "https://v1.vuepress.vuejs.org"
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "Guide",
          "collapsable": false,
          "children": [
            "",
            "how-to-use"
          ]
        },
        {
          "title": "Typography",
          "collapsable": false,
          "children": [
            "fonts",
            "text-styling",
            "css-classes"
          ]
        },
        {
          "title": "Components",
          "collapsable": false,
          "children": [
            "components",
            "button"
          ]
        }
      ]
    }
  }
}